name: Dump CloudFront
on:
  push:
    branches:
      - corgi
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dump-cf:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::121774052880:role/cicdRole
          
      - name: Dump CloudFront
        run: |
          aws cloudfront list-distributions > dists.json
          cat dists.json
          
          # get specific distribution configs
          for id in $(jq -r '.DistributionList.Items[].Id' dists.json); do
            echo "Distribution $id"
            aws cloudfront get-distribution --id $id > dist_$id.json
            cat dist_$id.json
          done
